### ISSUE TITLE
Show LeaderBoard

### ISSUE THREAD

**Issue by astandre** [JamesJose7/lol-data-analyzer#34]
Como administrador del club quiero poder registrar miembros del club al sistema, para poder dar un seguimiento a su desempeño en las partidas que se juegan en el club.

**Comment by JamesJose7** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(20) Mostrar leaderboard](https://trello.com/c/62TvZsPf/14-20-mostrar-leaderboard)
